language: csharp
dotnet: 6.0
os: linux
dist: xenial
mono: none
sudo: required

install:
before_script:
script:
- dotnet build -c Release
- dotnet test test/Binance.Client.Websocket.Tests -c Release
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd src/Binance.Client.Websocket && dotnet pack /p:PackageVersion=2.1.$TRAVIS_BUILD_NUMBER -c Release && cd bin/Release && dotnet nuget push **/*.2.1.$TRAVIS_BUILD_NUMBER.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master